[general]
dbpath = ./comments.db
host =
    https://356189.xyz
    https://356189.xyz/
    http://localhost:1313
    http://127.0.0.1:1313
    http://localhost:1313/
    http://127.0.0.1:1313/
# Edit/delete window for comment authors: 7 days = 604800 seconds.
max-age = 604800
notify = stdout

[server]
listen = http://0.0.0.0:1212/
public-endpoint = https://logcomments.356189.xyz
samesite = None

[guard]
enabled = false

[markup]
options = indent-code, autolink, strikethrough, superscript, footnotes

[hash]
salt = E7Y89EY78SD78SA7D8A7SD8A7SD8A
algorithm = pbkdf2
