[general]
dbpath = ./comments.db
host =
    http://localhost:1313
    http://127.0.0.1:1313
    http://localhost:1313/
    http://127.0.0.1:1313/
max-age = 7d
notify = stdout

[server]
listen = http://0.0.0.0:1212/

[guard]
enabled = false

[markup]
options = indent-code, autolink, strikethrough, superscript, footnotes

[hash]
salt = E7Y89EY78SD78SA7D8A7SD8A7SD8A
algorithm = pbkdf2
